variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - export ORYX_VERSION=${CI_BUILD_REF_SLUG}_$(date -I)
    - mkdir -p ~/ci-cache/{sstate-cache,downloads}
    - ln -sfn ~/ci-cache/sstate-cache build/
    - ln -sfn ~/ci-cache/downloads build/
    - source build/conf/setenv

qemux86:
    script:
        - ./scripts/run-build.py -M qemux86 -V ${ORYX_VERSION}

raspberrypi3:
    script:
        - ./scripts/run-build.py -M raspberrypi3 -V ${ORYX_VERSION}

raspberrypi3-64:
    script:
        - ./scripts/run-build.py -M raspberrypi3-64 -V ${ORYX_VERSION}

beaglebone-yocto:
    script:
        - ./scripts/run-build.py -M beaglebone-yocto -V ${ORYX_VERSION}
