variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - ./patches/apply.sh

qemux86:
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) qemux86

raspberrypi3:
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) raspberrypi3

raspberrypi3-64:
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) raspberrypi3-64

beaglebone-yocto:
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) beaglebone-yocto
