variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build

before_script:
    - ./patches/apply.sh

qemux86:
    stage: build
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) qemux86
    artifacts:
        paths:
            - build/pub
        expire_in: 1 week

qemux86-64:
    stage: build
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) qemux86-64
    artifacts:
        paths:
            - build/pub
        expire_in: 1 week

qemuarm:
    stage: build
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) qemuarm
    artifacts:
        paths:
            - build/pub
        expire_in: 1 week

qemuarm64:
    stage: build
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) qemuarm64
    artifacts:
        paths:
            - build/pub
        expire_in: 1 week

raspberrypi3:
    stage: build
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) raspberrypi3
    artifacts:
        paths:
            - build/pub
        expire_in: 1 week

raspberrypi3-64:
    stage: build
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) raspberrypi3-64
    artifacts:
        paths:
            - build/pub
        expire_in: 1 week

docs:
    stage: build
    script:
        - cd docs
        - make html
        - make latexpdf
    artifacts:
        paths:
            - docs/_build/html
            - docs/_build/latex/*.pdf
        expire_in: 1 week
