variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build

before_script:
    - ./patches/apply.sh

after_script:
    - rm -rf build/tmp
    - rm -rf build/cache

docs:
    stage: build
    script:
        - ./scripts/build.py --docs
    artifacts:
        paths:
            - build/images
        expire_in: 1 week

native-images:
    stage: build
    script:
        - ./scripts/build.py -k -V ${CI_BUILD_REF_SLUG} -S native -A host-test --all-machines --rm-work --dl-dir ~/ci-cache/downloads --sstate-dir ~/ci-cache/sstate-cache
    artifacts:
        paths:
            - build/images
        expire_in: 1 week

guest-images:
    stage: build
    script:
        - ./scripts/build.py -k -V ${CI_BUILD_REF_SLUG} -S guest -A minimal --all-machines --rm-work --dl-dir ~/ci-cache/downloads --sstate-dir ~/ci-cache/sstate-cache
    artifacts:
        paths:
            - build/images
        expire_in: 1 week
