variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - ./patches/apply.sh

qemux86:
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) qemux86
    artifacts:
        paths:
            - build/pub
        expire_in: 1 week

raspberrypi3:
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) raspberrypi3
    artifacts:
        paths:
            - build/pub
        expire_in: 1 week

raspberrypi3-64:
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) raspberrypi3-64
    artifacts:
        paths:
            - build/pub
        expire_in: 1 week

beaglebone-yocto:
    script:
        - ./ci/run.py ${CI_BUILD_REF_SLUG}_$(date -I) beaglebone-yocto
    artifacts:
        paths:
            - build/pub
        expire_in: 1 week
