
# Send a repo dispatch on pushes to the dunfell branch in order to trigger a build

name: repo_dispatch

on:
  push:
    branches: [ dunfell ]
#  pull_request:
#    branches: [ dunfell ]
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: obelus
    steps:
      - name: Dispatch on push to dunfell
        run: |
          curl -X POST https://api.github.com/repos/NetworkGradeLinux/mion-ci/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "push", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
